FROM nginx:alpine

COPY dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker-runtime-config.sh /docker-entrypoint.d/40-taskview-runtime-config.sh
RUN chmod +x /docker-entrypoint.d/40-taskview-runtime-config.sh

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
